# ----
# Site

title: Streamtime
email: info@streamtime.ai
description: Streamtime is a universal management plane to manage your kafka clusters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: streamtime-ai
github_username:  streamtime-ai
form_url: "https://script.google.com/macros/s/AKfycbyPCGRAnnJAeB4VfgwmIgm3tCQwp1FfxB_hPYCqt7NcG-ewK6ODqgbP-Pdc5mzsIH36/exec"
captcha_site_key: "6Leaq2srAAAAAJTYz6ek7aJ_LV7qCZEeEgZxxlpd"

google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Stream Time
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
